# # Illegal annotation of built-in vocabulary
#
# **Problem:** Formatting characters are used in a label. This may cause issues when trying to reference the entity by label.
#
# **Solution:** Remove formatting characters from label.

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  VALUES ?entity {
      rdf:type
    }
  ?entity ?property ?value
}
ORDER BY ?entity
