PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE 
  {{?entity owl:deprecated ?dep .
    FILTER regex(str(?dep), "true") .
    ?value ?property ?entity }
   UNION 
   {VALUES ?property {rdfs:subClassOf}
    ?entity owl:deprecated ?dep .
    FILTER regex(str(?dep), "true") .
    ?entity ?property ?value }}