## title: duplicate definition violation(s)
## severity: 5
## ---

PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?entity ?property ?value WHERE 
  {VALUES ?property {obo:IAO_0000115}
   ?entity obo:IAO_0000115 ?value .
   ?entity2 obo:IAO_0000115 ?value . 
   FILTER (?entity != ?entity2)
   FILTER (!isBlank(?entity))}