PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE 
  {VALUES ?property {owl:equivalentClass}
   ?entity ?property ?value .
   FILTER (!isBlank(?value))
   FILTER EXISTS {?axiom owl:annotatedSource ?entity .
   	              ?axiom owl:annotatedTarget ?values .
   	              ?axiom owl:annotatedProperty owl:equivalentClass .
   	              ?axiom oboInOwl:is_inferred ?inf .
                  FILTER regex(str(?inf), "true")}}
