## title: equivalent pair violation(s)
## severity: 5
## ---

PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?entity ?property ?value WHERE 
  {VALUES ?property {owl:equivalentClass}
   ?entity ?property ?value .
   FILTER NOT EXISTS {FILTER isBlank(?value)}}