## title: label cardinality violation(s)
## severity: 5
## ---

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE 
  {{?entity ?any ?o
    FILTER NOT EXISTS {?entity rdfs:label ?value}
    FILTER NOT EXISTS {?entity a owl:Ontology}
    FILTER NOT EXISTS {?entity owl:deprecated true}}
   UNION
   {VALUES ?property {rdfs:label}
   	?entity ?property ?value .
    ?entity ?property ?value2 .
    FILTER (?value != ?value2) .
    FILTER NOT EXISTS {?entity owl:deprecated true}}}