PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX GO: <http://purl.obolibrary.org/obo/GO_>
PREFIX BFO: <http://purl.obolibrary.org/obo/BFO_>

CONSTRUCT {
  GO:0031981 BFO:0000050 ?whole . # 'nuclear lumen' 'part of'
}
WHERE {
  GO:0031981 rdfs:subClassOf [ # nuclear lumen
    rdf:type owl:Restriction ;
    owl:onProperty BFO:0000050 ; # part of
    owl:someValuesFrom ?whole
  ] .
}
